{% set name = "mkdocs-macros-plugin" %}
{% set version = "1.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 17c7fd1a49b94defcdb502fd453d17a1e730f8836523379d21292eb2be4cb523

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - setuptools
    - python >=3.8
  run:
    - python >=3.8
    - mkdocs >=0.17
    - hjson-py
    - jinja2
    - packaging
    - pathspec
    - python-dateutil
    - super-collections
    - termcolor
    - pyyaml

test:
  imports:
    - mkdocs_macros

about:
  home: https://github.com/fralau/mkdocs_macros_plugin
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Unleash the power of MkDocs with macros and variables

extra:
  recipe-maintainers:
    - marcelotrevisani
    - hoechenberger
