{% set name = "mkdocs-macros-plugin" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe348d75f01c911f362b6d998c57b3d85b505876dde69db924f2c512c395c328

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - jinja2
    - mkdocs >=0.17
    - mkdocs-material >=6.2
    - python >=3.5
    - python-dateutil
    - pyyaml
    - termcolor

test:
  imports:
    - mkdocs_macros

about:
  home: https://github.com/fralau/mkdocs_macros_plugin
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Unleash the power of MkDocs with macros and variables

extra:
  recipe-maintainers:
    - marcelotrevisani
    - hoechenberger
